Feature
latifa-wakili/Roman-Numeral-Converter pull request #1
Opened 2024-06-29 03:48 UTC by latifa-wakili

2024-06-29 04:42 UTC, latifa-wakili commented
@Sumita-BLH

2024-06-29 10:52 UTC, S-BLH commented
you implemented all the necessary things for the project, well done latifa jan.

2024-06-29 11:24 UTC, latifa-wakili commented
@ahzamir

2024-06-29 16:18 UTC, ahzamir requested changes
@latifa-wakili 

- Although you have done a great job by implementing lots of requirements but still your project has some issues check the below comments for more details:

2024-06-29 16:18 UTC, ahzamir commented on script.js
> +    for (let i = 0; i < romanNumerals.length; i) {
- Your loop runs unlimited time as you did not change the array order in your loop try this line instead:
  - Copy this line and paste it to your code to solve the issue.
```javascript
for (let i = 0; i < romanNumerals.length; i++) {
```

- In here I added `i++` to change the array loop order while it runs to + 1

2024-06-29 16:18 UTC, ahzamir commented on README.md
> +(Roman-NC.png)
- Add your project Demo Image here using this line of code:

```
![Demo](HERE YOUR PROJECT IMAGE LINK)
```

2024-06-29 16:18 UTC, ahzamir commented on README.md
> +-JS
Add a space between `-JS` make it `- JS`

2024-06-29 16:18 UTC, ahzamir commented on README.md
> +```
- Remove this and paste this instead:
  - Dont forget to remove the parenthesis after you pasted `( )`

```
(```
code .
```)
```

2024-06-29 18:26 UTC, latifa-wakili commented
@ahzamir bcz of  JS linters erros i changed some of my codes pls rereveiw it now

2024-07-01 07:05 UTC, ahzamir commented
@latifa-wakili 

- Your code is not functioning well and it is not working properly.

2024-07-02 04:32 UTC, latifa-wakili commented
@ahzamir finally I solved my linters error and my code works 
please rereview my repo for approval

2024-07-02 10:43 UTC, ahzamir approved these changes
### Hi @latifa-wakili 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Don't forget to deploy your project and share on Social Media.
- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/latifa-wakili/Roman-Numeral-Converter/assets/96838030/802c2cb5-ace4-4b4b-98ac-39368b6e9bfc)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-07-02 10:47 UTC, merged